[tool.poetry]
name = "pypahe"
version = "1.0.0"
description = "pypahe is a PYthon PAckage HElper command-line tool"
license = "GPL-3.0-only"
authors = ["Antoine <achatain@users.noreply.github.com>"]
homepage = "https://bonjour.software"
repository = "https://github.com/bonjoursoftware/pypahe"

[tool.poetry.dependencies]
python = "^3.9"
requests = "2.25.1"

[tool.poetry.dev-dependencies]
black = "21.5b1"
flake8 = "3.9.2"
httpretty = "1.1.1"
mypy = "0.812"
pytest = "6.2.4"
pytest-cov = "2.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
